[package]
name = "Server"
version = "0.1.0"
edition = "2024"

[dependencies]
ecb="0.1.2"
aes="0.8.4"
hex-literal="1.0.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
common = {path = "../common"}